name = "letter-swipe"

[build]
command = "npm install && npm run build"
output_directory = "dist"

[build.environment]
NODE_VERSION = "20.15.1"
NPM_VERSION = "10.7.0"

# Optional: Configure custom domains and deployment branches
# [deployment]
# routes = [
#     { pattern = "/*", zone_name = "" }, # Add your domain here if using a custom domain
# ]

[env.production]
# Production-specific settings can go here

[env.preview]
# Preview branch settings can go here
